--table name  delivery

1.
;WITH CTE AS(
SELECT DRIVER_ID,count(id) IDCNT  from delivery where  CONVERT(VARCHAR(6,ATTEMPT_TIMESTAMP,112)='202409'
AND delivery_status='COMPLETED'
HAVING COUNT(ID)>=5 )
select A.DRIVER_ID,count(id) TOTAL_DELIVERIES,SUM((IDCNT/count(id))*100) SUCUESS_RATE
 from delivery A 
JOIN CTE B ON A.DRIVER_ID=B.DRIVER_ID
 where 
AND CONVERT(VARCHAR(6,ATTEMPT_TIMESTAMP,112)='202409'
HAVING SUM((IDCNT/count(id))*100)>90
